github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
baseurl: /conjur
title: Conjur
