# hosts.yml
- !host jenkins-01
- !host jenkins-02
- !host jenkins-03
- !host docker-registry-01
- !host release-01

- !grant
  role: !layer prod/jenkins
  member:
  - !host jenkins-01
  - !host jenkins-02
  - !host jenkins-03

- !grant
  role: !layer prod/release-bot
  member:
  - !host release-01

- !grant
  roles:
  - !layer dev/docker-registry
  - !layer prod/docker-registry
  members:
  - !host docker-registry-01
