pg:
  image: postgres:9.3
possum:
  image: possum-dev
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    CONJUR_ACCOUNT: cucumber
    CONJUR_PASSWORD_ALICE: secret
    POSSUM_DATA_KEY:
  volumes:
  - ..:/src/possum
  links:
  - pg:pg
cucumber:
  image: possum-dev
  entrypoint: bash
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    CONJUR_APPLIANCE_URL: http://possum:3000
    POSSUM_DATA_KEY:
  volumes:
  - ..:/src/possum
  links:
  - possum:possum
  - pg:pg
