pg:
  image: postgres:9.3
  
conjur:
  image: possum
  command: server -p 80 -a dev -f /run/empty.yml
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    POSSUM_ADMIN_PASSWORD: secret
    POSSUM_DATA_KEY:
    RAILS_ENV: production
  volumes:
  - ./empty.yml:/run/empty.yml:ro
  links:
  - pg

cli:
  build: .
  dockerfile: Dockerfile.cli
  entrypoint: sleep
  command: infinity
  environment:
    CONJUR_APPLIANCE_URL: http://conjur
    CONJUR_ACCOUNT: dev
    CONJUR_AUTHN_LOGIN: admin
  links:
  - conjur
