---
apiVersion: v1
kind: Service
metadata:
  name: conjur
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: conjur
---
apiVersion: v1
kind: Pod
metadata:
  name: conjur
  labels:
    app: conjur
spec:
  containers:
  - image: conjur-dev
    imagePullPolicy: IfNotPresent
    name: conjur
    command: [ sleep ]
    args: [ infinity ]
    env:
    - name: DATABASE_URL
      value: postgres://postgres@pg/postgres
    - name: RAILS_ENV
      value: development
    - name: CONJUR_DATA_KEY
      valueFrom:
        secretKeyRef:
          name: conjur-data-key
          key: data-key
    volumeMounts:
    - mountPath: /src/conjur
      name: local-dev
      
  - image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent
    name: kubectl
    command: [ kubectl, proxy, "-p", "8080" ]

  volumes:
    - name: local-dev
      hostPath:
        path: /Users/kgilpin/source/conjur/conjur
