---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - image: authenticator
    imagePullPolicy: IfNotPresent
    name: authenticator
    env:
    - name: CONJUR_APPLIANCE_URL
      value: http://conjur
    - name: CONJUR_AUTHN_URL
      value: http://conjur/authn-kubernetes
    - name: CONJUR_ACCOUNT
      value: mycorp
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - mountPath: /run/conjur
      name: conjur-access-token

  - image: myapp
    imagePullPolicy: IfNotPresent
    name: myapp
    env:
    - name: CONJUR_APPLIANCE_URL
      value: http://conjur
    - name: CONJUR_ACCOUNT
      value: mycorp
    volumeMounts:
    - mountPath: /run/conjur/
      name: conjur-access-token
      readonly: true

  volumes:
    - name: conjur-access-token
      emptyDir:
        medium: Memory
