pg:
  image: postgres:9.3
  
possum:
  image: possum
  command: server -f /run/possum/policy/Conjurfile
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    CONJUR_ACCOUNT: cucumber
    CONJUR_PASSWORD_KEVIN: kevin
    CONJUR_PASSWORD_BOB: bob
    POSSUM_DATA_KEY:
  volumes:
  - ./run:/run/possum/policy
  links:
  - pg:pg
  
watch:
  image: possum
  command: policy watch /run/possum/policy/load
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    CONJUR_ACCOUNT: cucumber
    CONJUR_PASSWORD_KEVIN: kevin
    CONJUR_PASSWORD_BOB: bob
    POSSUM_DATA_KEY:
  volumes:
  - ./run:/run/possum/policy
  links:
  - pg:pg

cli:
  build: .
  dockerfile: Dockerfile.cli
  environment:
    CONJUR_APPLIANCE_URL: http://possum
    CONJUR_AUTHN_LOGIN: alice
    CONJUR_AUTHN_API_KEY: secret
    CONJUR_ACCOUNT: cucumber
  links:
  - possum:possum
