pg:
  image: postgres:9.3

possum:
  image: conjurinc/possum
  command: server -a example -f /var/lib/policy/bootstrap.yml
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    POSSUM_ADMIN_PASSWORD: secret
    POSSUM_DATA_KEY:
  volumes:
  - ./policy:/var/lib/policy
  links:
  - pg:pg

client:
  build: .
  entrypoint: bash
  environment:
    POSSUM_URL: http://possum
    POSSUM_ADMIN_PASSWORD: secret
    POSSUM_ACCOUNT: example
    POSSUM_LOGIN: admin
    POSSUM_PASSWORD: secret
  links:
  - possum:possum
