pg:
  image: postgres:9.3
  
possum:
  image: possum
  command: server -f /run/possum/policy/Conjurfile
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    CONJUR_ACCOUNT: cucumber
    POSSUM_ADMIN_PASSWORD: admin
    CONJUR_PASSWORD_KEVIN: kevin
    CONJUR_PASSWORD_DAVE: dave
    CONJUR_PASSWORD_OTTO: otto
    POSSUM_DATA_KEY:
  volumes:
  - ./run:/run/possum/policy
  links:
  - pg:pg
  
watch:
  image: possum
  command: policy watch /run/possum/policy/load
  environment:
    DATABASE_URL: postgres://postgres@pg/postgres
    CONJUR_ACCOUNT: cucumber
    POSSUM_ADMIN_PASSWORD: admin
    CONJUR_PASSWORD_KEVIN: kevin
    CONJUR_PASSWORD_DAVE: dave
    CONJUR_PASSWORD_OTTO: otto
    POSSUM_DATA_KEY:
  volumes:
  - ./run:/run/possum/policy
  links:
  - pg:pg

cli:
  build: .
  dockerfile: Dockerfile.cli
  environment:
    CONJUR_APPLIANCE_URL: http://possum
    CONJUR_AUTHN_LOGIN: admin
    CONJUR_AUTHN_API_KEY: admin
    CONJUR_ACCOUNT: cucumber
  volumes:
  - .:/mnt/src
  - ./run:/run/possum/policy
  links:
  - possum:possum

ui:
  image: conjurinc/conjur-ui
  environment:
    CONJUR_APPLIANCE_URL: http://possum
    DH_PARAM_PEM:
  ports:
  - 443
  volumes:
  - ./dhparam.pem:/etc/ssl/certs/dhparam.pem
  links:
  - possum:possum

